# Project information
site_name: SSS Docs
site_url: https://net-byu.github.io/sss/
site_author: christopolise

# Repository
repo_name: NET-BYU/sss
repo_url: https://github.com/NET-BYU/sss

# Copyright
copyright: Copyright &copy; 2022 BYU NET Lab

theme: 
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/sss.png
  icon:
    logo: material/snake

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

edit_uri: edit/dev/docs/

plugins:
- mkdocstrings
- search
- git-revision-date-localized:
    enable_creation_date: true
