name: Check formatting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort
      - name: Analyzing the code with black
        run: |
          black --check --diff $(git ls-files '*.py')
      - name: Analyzing imports with isort
        run: |
          isort --profile black --check --diff $(git ls-files '*.py')
