name: Test on Raspberry Pi

on: [push]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.10.14"]
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update && sudo apt install -y libatlas-base-dev python3-pip python3-venv python3-dev libffi-dev build-essential libgl1-mesa-glx libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libjpeg-dev libpng-dev libfreetype6-dev libportmidi-dev

      - name: Set up Python version
        run: |
          echo $HOME
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"
          python -V
          python3 -V
          pyenv ${{ matrix.python-version }}
          python -V
          python3 -V

      # - name: Set up environment
      #   run: |
      #     rm -rf /tmp/test-${{ matrix.python-version }}
      #     mkdir /tmp/test-${{ matrix.python-version }}
      #     pwd
      #     python -V
      #     python3 -V
      #     pyenv local ${{ matrix.python-version }}
      #     python -V
      #     python3 -V
      #     rm -rf /tmp/test-${{ matrix.python-version }}

          
      #     python -V
      #     python3 -V
      #     python -m venv /tmp/test/.venv

      # - name: Install project dependencies
      #   run: |
      #     /tmp/test/.venv/bin/python -m pip install -r requirements.txt

      # - name: Run all demos to make sure they load
      #   run: |
      #     /tmp/test/.venv/bin/python main.py test

      # - name: Clean up code
      #   if: always()
      #   run: |
      #     rm -rf /tmp/test
